version: '3.3'
services:
  execution:
    container_name: "${CONTAINER_PREFIX}_execution"
    image: "${IMAGE_PREFIX}-execution"
    build:
      context: ./${EXECUTION_NODE}/build
      args:
        PROCESS_UID: $EXECUTION_UID
        PROCESS_GID: $EXECUTION_GID
    environment:
      - EXECUTION_DISC
      - ETH_TESTNET
    ports:
      - "${EXECUTION_DISC}:${EXECUTION_DISC}/tcp"
      - "${EXECUTION_DISC}:${EXECUTION_DISC}/udp"
    expose:
      - 8545
      - 8560
    volumes:
      - ./${EXECUTION_NODE}/run:/home/execution/run
      - ./shared:/shared

