version: "3"
services:
  beacon:
    environment:
      - PROXY_ENABLED=true
    depends_on:
      - proxy
  execution:
    environment:
      - PROXY_ENABLED=true
  proxy:
    container_name: "${CONTAINER_PREFIX}_proxy"
    image: "${IMAGE_PREFIX}-proxy"
    build:
      context: ./proxy
    expose:
      - 8560
    volumes:
      - ./proxy/run:/home/json_rpc_snoop/run
    depends_on:
      - execution

