global:
    scrape_interval: 15s

scrape_configs:
  - job_name: 'beacon'
    static_configs:
      - targets: ['beacon:5054']
  - job_name: 'validator'
    static_configs:
      - targets: ['validator:5064']
  - job_name: 'execution'
    static_configs:
      - targets: ['execution:6060']


