{
 "title": "Nethermind",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "query": { "query": "label_values(nethermind_group)" } },
   {
    "name": "enode",
    "query": {
     "query": "label_values({nethermind_group=\"$group\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Peers",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_sync_peers{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Block Number",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "nethermind_blocks{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      },
      {}
     ]
    },
    {
     "title": "Total difficulty",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "nethermind_total_difficulty{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      },
      {}
     ]
    },
    {
     "title": "Last difficulty",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "nethermind_last_difficulty{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      },
      {}
     ]
    },
    {
     "title": "Seconds per block",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "$__range_s/increase(nethermind_blocks{job=\"nethermind\", instance=\"$enode\", nethermind_group=\"$group\"}[$__range])"
      },
      {}
     ]
    },
    {
     "title": "Total difficulty diff",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "increase(nethermind_total_difficulty{job=\"nethermind\", instance=\"$enode\", nethermind_group=\"$group\"}[$__range])"
      },
      {}
     ]
    },
    {
     "title": "Traffic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_json_rpc_bytes_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "RPC Sent"
      },
      {
       "expr": "rate(nethermind_json_rpc_bytes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "RPC Received"
      },
      {
       "expr": "rate(nethermind_discovery_bytes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Dscv Sent"
      },
      {
       "expr": "rate(nethermind_discovery_bytes_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Dscv Received"
      },
      {
       "expr": "rate(nethermind_p2pbytes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "P2P Received"
      },
      {
       "expr": "rate(nethermind_p2pbytes_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "P2P Sent"
      }
     ]
    },
    {
     "title": "Version",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_version{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Engine API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execution Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "nethermind_forkchoice_upded_execution_time{instance=\"$enode\"}",
       "legendFormat": "Forkchoice Update execution Time(ms)"
      },
      {
       "expr": "nethermind_new_payload_execution_time{instance=\"$enode\"}",
       "legendFormat": "New Payload Execution Time"
      }
     ]
    },
    {
     "title": "Counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "nethermind_get_payload_requests{instance=\"$enode\"}",
       "legendFormat": "Get Payload Requests"
      },
      {
       "expr": "nethermind_number_of_transactions_in_get_payload{instance=\"$enode\"}",
       "legendFormat": "Transaction Count in Get Payload"
      }
     ]
    }
   ]
  },
  {
   "title": "AuRa Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks Sealed (total)",
     "type": "stat",
     "description": "Total number of sealed blocks",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_blocks_sealed{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Failed Block Seals (total)",
     "type": "stat",
     "description": "Total number of failed block seals",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_failed_block_seals{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Aura Step",
     "type": "graph",
     "description": "Current AuRa step",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_au_ra_step{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Blocks Production Indicator",
     "type": "stat",
     "description": "Indicator if blocks can be produced",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_can_produce_blocks{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Reported Malicious Misbehaviour",
     "type": "stat",
     "description": "Number of reported malicious misbehaviour validators",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_reported_malicious_misbehaviour{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Sealed Transactions",
     "type": "graph",
     "description": "Number of sealed transactions generated by engine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_sealed_transactions{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Reported Benign Misbehaviour",
     "type": "stat",
     "description": "Number of reported benign misbehaviour validators",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_reported_benign_misbehaviour{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Validators Count",
     "type": "stat",
     "description": "Number of current AuRa validators",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_validators_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "RANDAO Reveal Number",
     "type": "graph",
     "description": "RANDAO number of reveal number transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_reveal_number{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "POSDAO Emit Initiate Change",
     "type": "graph",
     "description": "POSDAO number of emit init change transactions",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_emit_initiate_change{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "RANDAO Commit Hash Transaction",
     "type": "graph",
     "description": "RANDAO number of commit hash transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_commit_hash_transaction{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Managed Memory"
      },
      {
       "expr": "process_working_set_bytes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "dotnet_total_memory_bytes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"} -   nethermind_memory_used_by_cache{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Managed Memory without pruning cache"
      }
     ]
    },
    {
     "title": "Memory Growth (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "deriv(dotnet_total_memory_bytes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[2m]) > 0",
       "legendFormat": "Managed Memory",
       "target": "*.Nethermind_Runner.*.*.*.*.gauge.*.Process_Physical_Memory"
      }
     ]
    },
    {
     "title": "GC (per minute)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"0\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Gen 0"
      },
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"1\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Gen 1"
      },
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"2\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Gen 2"
      }
     ]
    }
   ]
  },
  { "title": "Pruning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Caching Efficiency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_loaded_from_db_nodes_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "DB"
    },
    {
     "expr": "nethermind_loaded_from_rlp_cache_nodes_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "RLP Cache"
    },
    {
     "expr": "nethermind_loaded_from_cache_nodes_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Node Cache"
    },
    {
     "expr": "nethermind_rlp_cache_hits{nethermind_group=\"$group\", job=\"nethermind\", instance=\"$enode\"}",
     "legendFormat": "TrieStore RLP Cache Hits"
    }
   ]
  },
  {
   "title": "Pruning Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nethermind_memory_used_by_cache{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Pruning Levels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_committed_nodes_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "nethermind_persisted_node_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Persisted"
    },
    {
     "expr": "nethermind_cached_nodes_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "nethermind_replaced_nodes_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Replaced"
    },
    {
     "expr": "nethermind_pruned_persisted_nodes_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Pruned Persisted"
    },
    {
     "expr": "nethermind_pruned_transient_nodes_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Pruned Transient"
    }
   ]
  },
  {
   "title": "Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_snapshot_persistence_time{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Persistence"
    },
    {
     "expr": "nethermind_pruning_time{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Pruning"
    },
    {
     "expr": "nethermind_deep_pruning_time{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block processing time (ms)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_last_block_processing_time_in_ms{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Blocks (per second)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_blocks{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])",
       "legendFormat": "Blocks"
      }
     ]
    },
    {
     "title": "Sync Peers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Sync Peers" }
     ],
     "targets": [
      {
       "expr": "nethermind_sync_peers{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Sync Peers"
      }
     ]
    },
    {
     "title": "State Synced (in bytes)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nethermind_state_synced{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "State"
      },
      {
       "expr": "rate(nethermind_state_synced{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[60m])*3600",
       "legendFormat": "State/h"
      },
      {
       "expr": "nethermind_snap_state_synced{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "SnapState"
      },
      {
       "expr": "rate(nethermind_snap_state_synced{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[60m])*3600",
       "legendFormat": "SnapState/h"
      }
     ]
    },
    {
     "title": "SnapSync - Accounts, Storage and ByteCodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_snap_synced_storage_slots{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Storage slots"
      },
      {
       "expr": "nethermind_snap_synced_accounts{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Accounts"
      },
      {
       "expr": "nethermind_snap_synced_codes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Codes"
      }
     ]
    },
    {
     "title": "Fast Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_fast_headers{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Headers"
      },
      {
       "expr": "nethermind_fast_bodies{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Bodies"
      },
      {
       "expr": "nethermind_fast_receipts{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Receipts"
      }
     ]
    },
    {
     "title": "Blocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_blocks{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "CPU time (tracks restarts)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[$__interval])",
       "legendFormat": "CPU time"
      }
     ]
    }
   ]
  },
  {
   "title": "JSON RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "JSON RPC (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_json_rpc_successes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "RPC Successes"
      },
      {
       "expr": "rate(nethermind_json_rpc_errors{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "RPC Errors"
      },
      {
       "expr": "rate(nethermind_json_rpc_request_deserialization_failures{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Deserialization Failures"
      },
      {
       "expr": "rate(nethermind_json_rpc_invalid_requests{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Invalid Requests"
      }
     ]
    },
    {
     "title": "JSON RPC (total)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nethermind_json_rpc_requests{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "RPC Requests"
      },
      {
       "expr": "nethermind_json_rpc_successes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "RPC Successes"
      },
      {
       "expr": "nethermind_json_rpc_errors{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "RPC Errors"
      },
      {
       "expr": "nethermind_json_rpc_request_deserialization_failures{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Deserialization Failures"
      },
      {
       "expr": "nethermind_json_rpc_invalid_requests{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Invalid Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections (per minute)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_incoming_connections{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Incoming Connections"
      },
      {
       "expr": "rate(nethermind_outgoing_connections{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Outgoing Connections"
      },
      {
       "expr": "rate(nethermind_handshakes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Handshakes"
      },
      {
       "expr": "rate(nethermind_hellos_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Hellos Sent"
      },
      {
       "expr": "rate(nethermind_hellos_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Hellos Received"
      },
      {
       "expr": "rate(nethermind_statuses_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Statuses Sent"
      },
      {
       "expr": "rate(nethermind_statuses_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Statuses Received"
      }
     ]
    },
    {
     "title": "Pending Txs (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_pending_transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Received"
      },
      {
       "expr": "rate(nethermind_pending_transactions_known{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Already Known"
      },
      {
       "expr": "rate(nethermind_pending_transactions_discarded{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Discarded"
      },
      {
       "expr": "rate(nethermind_pending_transactions_too_far_in_future{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Too far in future"
      },
      {
       "expr": "rate(nethermind_pending_transactions_too_low_fee{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Too low fee"
      },
      {
       "expr": "rate(nethermind_pending_transactions_added{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Added (all)"
      },
      {
       "expr": "rate(nethermind_pending1559transactions_added{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Added (1559)"
      },
      {
       "expr": "rate(nethermind_pending_transactions_evicted{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Evicted"
      },
      {
       "expr": "rate(nethermind_pending_transactions_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Sent txs"
      },
      {
       "expr": "rate(nethermind_pending_transactions_hashes_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Sent hashes"
      }
     ]
    },
    {
     "title": "Disconnects (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_too_many_peers_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Too Many Peers"
      },
      {
       "expr": "rate(nethermind_client_quitting_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Client Quitting"
      },
      {
       "expr": "rate(nethermind_receive_message_timeout_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Receive Timeouts"
      },
      {
       "expr": "rate(nethermind_already_connected_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Already Connected"
      },
      {
       "expr": "rate(nethermind_breach_of_protocol_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Breach of Protocol"
      },
      {
       "expr": "rate(nethermind_incompatible_p2pdisconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Incompatible P2P"
      },
      {
       "expr": "rate(nethermind_null_node_identity_disconnects{job=\"nethermind\",_instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Null Identity"
      },
      {
       "expr": "rate(nethermind_unexpected_identity_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Unexpected Identity"
      },
      {
       "expr": "rate(nethermind_useless_peer_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Useless Peer"
      },
      {
       "expr": "rate(nethermind_diconnect_requested_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Requested"
      },
      {
       "expr": "rate(nethermind_tcp_subsystem_error_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "TCP Error"
      },
      {
       "expr": "rate(nethermind_same_as_self_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Same as Self"
      },
      {
       "expr": "rate(nethermind_other_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Eth62, Eth63, Eth65, Eth66 (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_eth62get_block_headers_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetBlockHeaders eth62"
      },
      {
       "expr": "rate(nethermind_eth62block_headers_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "BlockHeaders eth62"
      },
      {
       "expr": "rate(nethermind_eth62get_block_bodies_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetBlockBodies eth62"
      },
      {
       "expr": "rate(nethermind_eth62block_bodies_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "BlockBodies eth62"
      },
      {
       "expr": "rate(nethermind_eth62transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Txs received eth62"
      },
      {
       "expr": "rate(nethermind_eth65new_pooled_transaction_hashes_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "TxHashes sent eth65"
      },
      {
       "expr": "rate(nethermind_eth65new_pooled_transaction_hashes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "TxHashes received eth65"
      },
      {
       "expr": "rate(nethermind_eth65get_pooled_transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Txs requests received eth65"
      },
      {
       "expr": "rate(nethermind_eth65get_pooled_transactions_requested{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Txs requested eth65"
      },
      {
       "expr": "rate(nethermind_eth65pooled_transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Txs received eth65"
      },
      {
       "expr": "rate(nethermind_eth62new_block_hashes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "NewBlockHashes eth62"
      },
      {
       "expr": "rate(nethermind_eth62new_block_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "NewBlock eth62"
      },
      {
       "expr": "rate(nethermind_eth63get_node_data_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetNodeData eth63"
      },
      {
       "expr": "rate(nethermind_eth63node_data_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "NodeData eth63"
      },
      {
       "expr": "rate(nethermind_eth63get_receipts_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetReceipts eth63"
      },
      {
       "expr": "rate(nethermind_eth63receipts_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Receipts eth63"
      },
      {
       "expr": "rate(nethermind_eth66get_block_headers_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetBlockHeaders eth66"
      },
      {
       "expr": "rate(nethermind_eth66block_headers_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "BlockHeaders eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_block_bodies_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetBlockBodies eth66"
      },
      {
       "expr": "rate(nethermind_eth66block_bodies_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "BlockBodies eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_pooled_transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Txs requests received eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_pooled_transactions_requested{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Txs requested eth66"
      },
      {
       "expr": "rate(nethermind_eth66pooled_transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Txs received eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_node_data_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetNodeData eth66"
      },
      {
       "expr": "rate(nethermind_eth66node_data_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "NodeData eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_receipts_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetReceipts eth66"
      },
      {
       "expr": "rate(nethermind_eth66receipts_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Receipts eth66"
      }
     ]
    },
    {
     "title": "Snap Sync (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_snap_get_account_range_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetAccountRange received"
      },
      {
       "expr": "rate(nethermind_snap_get_account_range_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetAccountRange sent"
      },
      {
       "expr": "rate(nethermind_snap_account_range_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "AccountRange received"
      },
      {
       "expr": "rate(nethermind_snap_get_storage_ranges_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetStorageRanges received"
      },
      {
       "expr": "rate(nethermind_snap_get_storage_ranges_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetStorageRanges sent"
      },
      {
       "expr": "rate(nethermind_snap_storage_ranges_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "StorageRanges received"
      },
      {
       "expr": "rate(nethermind_snap_get_byte_codes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetByteCodes received"
      },
      {
       "expr": "rate(nethermind_snap_get_byte_codes_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetByteCodes sent"
      },
      {
       "expr": "rate(nethermind_snap_byte_codes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "ByteCodes received"
      },
      {
       "expr": "rate(nethermind_snap_get_trie_nodes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetTrieNodes received"
      },
      {
       "expr": "rate(nethermind_snap_get_trie_nodes_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "GetTrieNodes sent"
      },
      {
       "expr": "rate(nethermind_snap_trie_nodes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "TrieNodes received"
      }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receipts DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_receipts_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[10s])",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_receipts_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[10s])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Code DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_code_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_code_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "State Tree",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_state_tree_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_state_tree_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Block Info DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_block_infos_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_block_infos_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "State DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_state_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_state_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Writes"
      },
      {
       "expr": "rate(nethermind_state_db_in_pruning_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Pruning Writes"
      }
     ]
    },
    {
     "title": "Storage Tree",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_storage_tree_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_storage_tree_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Trie Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_tree_node_rlp_decodings{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "RLP.Encode"
      },
      {
       "expr": "rate(nethermind_tree_node_rlp_encodings{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "RLP.Decode"
      },
      {
       "expr": "rate(nethermind_tree_node_hash_calculations{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Keccak"
      }
     ]
    },
    {
     "title": "Other DB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_other_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[10s])",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_other_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[10s])",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Blocks DB (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_blocks_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_blocks_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    },
    {
     "title": "Header DB (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_header_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Reads"
      },
      {
       "expr": "rate(nethermind_header_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "TxPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tx Count",
     "type": "graph",
     "description": "Information about incoming transactions",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_transaction_count{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "DarkPool",
     "type": "graph",
     "description": "Unknown transactions in blocks",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "nethermind_dark_pool_ratio_level1{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "Level1 (not known)"
      },
      {
       "expr": "nethermind_dark_pool_ratio_level2{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
       "legendFormat": "level2 (not pending)"
      }
     ]
    },
    {
     "title": "1559-type transactions ratio",
     "type": "timeseries",
     "description": "Ratio of 1559-type transactions in the block.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "nethermind_eip1559transactions_ratio{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
      }
     ]
    },
    {
     "title": "Incoming transactions",
     "type": "graph",
     "description": "Information about incoming transactions",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_pending_transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "received"
      },
      {
       "expr": "rate(nethermind_pending_transactions_discarded{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "discarded"
      },
      {
       "expr": "rate(nethermind_pending_transactions_known{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "discarded already known"
      },
      {
       "expr": "rate(nethermind_pending_transactions_too_low_fee{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "discarded fee too low"
      },
      {
       "expr": "rate(nethermind_pending_transactions_added{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "added"
      },
      {
       "expr": "rate(nethermind_pending_transactions_evicted{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
       "legendFormat": "evicted"
      }
     ]
    }
   ]
  }
 ]
}