{
 "title": "SyncMetrics",
 "time": { "from": "now-280m", "to": "now-250m" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chain Segment Percent Failed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "( rate(beacon_processor_chain_segment_failed_total[1m]) / (rate(beacon_processor_chain_segment_success_total[1m]) + rate(beacon_processor_chain_segment_failed_total[1m])) ) * 100",
     "legendFormat": "percent failed"
    }
   ]
  },
  {
   "title": "Syncing chain counts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sync_range_chains", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Lighthouse Resident Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Chain Segment Outcome",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(beacon_processor_chain_segment_success_total[1m])",
     "legendFormat": "Success [Hz]"
    },
    {
     "expr": "rate(beacon_processor_chain_segment_failed_total[1m])",
     "legendFormat": "Failed [Hz]"
    }
   ]
  },
  {
   "title": "Peers per sync status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sync_peers_per_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "10m Average RPC Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "rate(libp2p_rpc_requests_total{}[10m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Chain Segment Time Bucket",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(beacon_processor_worker_time_bucket{type=\"chain_segment\", le=~\"0.05|0.1|0.01|0.005|0.25\"}[30s])",
     "legendFormat": "{{le}} sec"
    }
   ]
  },
  {
   "title": "Epoch Boundaries since Finalization (Min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "Epochs" }
   ],
   "targets": [
    {
     "expr": "slotclock_present_epoch - beacon_head_state_finalized_epoch",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Average Load (loadavg 1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "system_loadavg_1", "legendFormat": "Load" }
   ]
  },
  {
   "title": "Chain Segment Work Events Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "beacon_processor_work_events_rx_count{type=\"chain_segment\"}",
     "legendFormat": "count"
    },
    {
     "expr": "rate(beacon_processor_work_events_rx_count{type=\"chain_segment\"}[1m])",
     "legendFormat": "frequency [Hz]"
    }
   ]
  },
  {
   "title": "Peer Penalty Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 21 },
   "targets": [
    {
     "expr": "increase(libp2p_report_peer_msgs_total{}[1m])",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "Chain Segment Work Events Started",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "beacon_processor_work_events_started_count{type=\"chain_segment\"}",
     "legendFormat": "count"
    },
    {
     "expr": "rate(beacon_processor_work_events_started_count{type=\"chain_segment\"}[1m])",
     "legendFormat": "Frequency [Hz]"
    }
   ]
  },
  {
   "title": "Sync slots per second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sync_slots_per_second", "legendFormat": "__auto" }
   ]
  }
 ]
}